/** Display labels for the protected CompatibilityCatalogContract keys. */
export const partSpecificationLabels: Record<string, string> = {
  CPU_SOCKET: '處理器插槽（例如 AM5）',
  CPU_GENERATION: '處理器世代',
  POWER_DRAW_WATTS: '耗電功率（W）',
  MOTHERBOARD_CHIPSET: '主機板晶片組',
  MEMORY_TYPE: '記憶體類型（例如 DDR5）',
  MEMORY_SLOT_COUNT: '記憶體插槽數量',
  MEMORY_MAX_CAPACITY_GB: '記憶體最大容量（GB）',
  MOTHERBOARD_FORM_FACTOR: '主機板尺寸',
  M2_SLOT_COUNT: 'M.2 插槽數量',
  SATA_PORT_COUNT: 'SATA 連接埠數量',
  MOTHERBOARD_CPU_EPS_8PIN_REQUIRED_COUNT: '主機板需要的處理器 8-pin 接頭數',
  MEMORY_MODULE_COUNT: '記憶體模組數量',
  MEMORY_KIT_CAPACITY_GB: '記憶體套組容量（GB）',
  GPU_LENGTH_MM: '顯示卡長度（mm）',
  GPU_RECOMMENDED_PSU_WATTS: '顯示卡建議電源功率（W）',
  GPU_PCIE_6_2PIN_REQUIRED_COUNT: '顯示卡需要的 PCIe 6+2-pin 接頭數',
  GPU_12VHPWR_REQUIRED_COUNT: '顯示卡需要的 12VHPWR 接頭數',
  STORAGE_INTERFACE: '儲存裝置介面',
  PSU_RATED_WATTS: '電源供應器額定功率（W）',
  PSU_PCIE_6_2PIN_COUNT: '電源 PCIe 6+2-pin 接頭數',
  PSU_12VHPWR_COUNT: '電源 12VHPWR 接頭數',
  PSU_CPU_EPS_8PIN_COUNT: '電源處理器 8-pin 接頭數',
  PSU_FORM_FACTOR: '電源供應器尺寸',
  CASE_SUPPORTED_MOTHERBOARD_FORM_FACTOR: '機殼支援的主機板尺寸',
  CASE_GPU_MAX_LENGTH_MM: '機殼可容納的顯示卡長度（mm）',
  CASE_COOLER_MAX_HEIGHT_MM: '機殼可容納的散熱器高度（mm）',
  CASE_SUPPORTED_PSU_FORM_FACTOR: '機殼支援的電源尺寸',
  COOLER_HEIGHT_MM: '散熱器高度（mm）',
}
