<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoSelect.Domain\DoSelect.Domain.csproj" />
  </ItemGroup>

</Project>
